version: '3'

services:
  nginx-proxy:
    image: nginx
    ports:
      - 3000:80
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - backend
      - frontend

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes: 
      - ./backend:/app
    ports: 
      - 3001:3000
    depends_on: 
      - mongodb

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports: 
      - 3002:3000

  mongodb:
    image: mongo:4.0
    ports: 
      - 27017:27017
    volumes: 
      - ./data/mongo:/data/db

  backend-test:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes: 
      - ./backend:/app
    environment: 
      NODE_ENV: test
    command: npm run watch-test
    depends_on: 
      - mongodb
