version: '3'

services:
  nginx-proxy:
    image: nginx
    ports:
      - 3000:80
    volumes: 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    volumes: 
      - ./backend:/app
    ports: 
      - 3001:3000

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    ports: 
      - 3002:3000